name: Deploy Landscape (livenet)
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Enter the tag to deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Release to ~mister-dister-dozzod-dozzod (livenet)"
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.JANEWAY_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: deploy
        name: Deploy
        run:
          ./.github/helpers/deploy.sh tloncorp/landscape garden mister-dister-dozzod-dozzod us-central1-a ${{ github.event.inputs.tag }}
        env:
          SSH_SEC_KEY: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          SSH_PUB_KEY: ${{ secrets.JANEWAY_SSH_PUB_KEY }}